# Pull the base docker image of python with tag 3.10.12
FROM grobid/grobid:0.7.1

# Install Pipenv
RUN pip install pipenv

# Change the working dir inside the container - cd /app
WORKDIR /app

# Copy main.py as source cod and req.txt as dependency
COPY *.py ./
COPY *.txt ./
COPY .env ./

# COPY Pipfile Pipfile.lock ./
# Install the dependency
# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

### Container Env same as local at this point
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8082"]
# CMD ["uvicorn" ,"-w", "4", "-k", "uvicorn.workers.UvicornWorker" , "--bind", "0.0.0.0:8000", "main:app"]
# gunicorn command to run the service with 4 worker nodes binding localhost/0.0.0.0 on port 8000 refering app inside the main.py
